/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProgramRouteImport } from './routes/_app/program'
import { Route as AppPengaturanRouteImport } from './routes/_app/pengaturan'
import { Route as AppPengajuanBaruRouteImport } from './routes/_app/pengajuan-baru'
import { Route as AppMustahikRouteImport } from './routes/_app/mustahik'
import { Route as AppLaporanRouteImport } from './routes/_app/laporan'
import { Route as AppDonaturRouteImport } from './routes/_app/donatur'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBantuanRutinRouteImport } from './routes/_app/bantuan-rutin'
import { Route as AppBantuanInsidentalRouteImport } from './routes/_app/bantuan-insidental'
import { Route as AppKasusCaseIdRouteImport } from './routes/_app/kasus.$caseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramRoute = AppProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPengajuanBaruRoute = AppPengajuanBaruRouteImport.update({
  id: '/pengajuan-baru',
  path: '/pengajuan-baru',
  getParentRoute: () => AppRoute,
} as any)
const AppMustahikRoute = AppMustahikRouteImport.update({
  id: '/mustahik',
  path: '/mustahik',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppDonaturRoute = AppDonaturRouteImport.update({
  id: '/donatur',
  path: '/donatur',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBantuanRutinRoute = AppBantuanRutinRouteImport.update({
  id: '/bantuan-rutin',
  path: '/bantuan-rutin',
  getParentRoute: () => AppRoute,
} as any)
const AppBantuanInsidentalRoute = AppBantuanInsidentalRouteImport.update({
  id: '/bantuan-insidental',
  path: '/bantuan-insidental',
  getParentRoute: () => AppRoute,
} as any)
const AppKasusCaseIdRoute = AppKasusCaseIdRouteImport.update({
  id: '/kasus/$caseId',
  path: '/kasus/$caseId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bantuan-insidental': typeof AppBantuanInsidentalRoute
  '/bantuan-rutin': typeof AppBantuanRutinRoute
  '/dashboard': typeof AppDashboardRoute
  '/donatur': typeof AppDonaturRoute
  '/laporan': typeof AppLaporanRoute
  '/mustahik': typeof AppMustahikRoute
  '/pengajuan-baru': typeof AppPengajuanBaruRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/program': typeof AppProgramRoute
  '/kasus/$caseId': typeof AppKasusCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bantuan-insidental': typeof AppBantuanInsidentalRoute
  '/bantuan-rutin': typeof AppBantuanRutinRoute
  '/dashboard': typeof AppDashboardRoute
  '/donatur': typeof AppDonaturRoute
  '/laporan': typeof AppLaporanRoute
  '/mustahik': typeof AppMustahikRoute
  '/pengajuan-baru': typeof AppPengajuanBaruRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/program': typeof AppProgramRoute
  '/kasus/$caseId': typeof AppKasusCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bantuan-insidental': typeof AppBantuanInsidentalRoute
  '/_app/bantuan-rutin': typeof AppBantuanRutinRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/donatur': typeof AppDonaturRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/mustahik': typeof AppMustahikRoute
  '/_app/pengajuan-baru': typeof AppPengajuanBaruRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/program': typeof AppProgramRoute
  '/_app/kasus/$caseId': typeof AppKasusCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bantuan-insidental'
    | '/bantuan-rutin'
    | '/dashboard'
    | '/donatur'
    | '/laporan'
    | '/mustahik'
    | '/pengajuan-baru'
    | '/pengaturan'
    | '/program'
    | '/kasus/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bantuan-insidental'
    | '/bantuan-rutin'
    | '/dashboard'
    | '/donatur'
    | '/laporan'
    | '/mustahik'
    | '/pengajuan-baru'
    | '/pengaturan'
    | '/program'
    | '/kasus/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bantuan-insidental'
    | '/_app/bantuan-rutin'
    | '/_app/dashboard'
    | '/_app/donatur'
    | '/_app/laporan'
    | '/_app/mustahik'
    | '/_app/pengajuan-baru'
    | '/_app/pengaturan'
    | '/_app/program'
    | '/_app/kasus/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/program': {
      id: '/_app/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof AppProgramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengajuan-baru': {
      id: '/_app/pengajuan-baru'
      path: '/pengajuan-baru'
      fullPath: '/pengajuan-baru'
      preLoaderRoute: typeof AppPengajuanBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mustahik': {
      id: '/_app/mustahik'
      path: '/mustahik'
      fullPath: '/mustahik'
      preLoaderRoute: typeof AppMustahikRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donatur': {
      id: '/_app/donatur'
      path: '/donatur'
      fullPath: '/donatur'
      preLoaderRoute: typeof AppDonaturRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bantuan-rutin': {
      id: '/_app/bantuan-rutin'
      path: '/bantuan-rutin'
      fullPath: '/bantuan-rutin'
      preLoaderRoute: typeof AppBantuanRutinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bantuan-insidental': {
      id: '/_app/bantuan-insidental'
      path: '/bantuan-insidental'
      fullPath: '/bantuan-insidental'
      preLoaderRoute: typeof AppBantuanInsidentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kasus/$caseId': {
      id: '/_app/kasus/$caseId'
      path: '/kasus/$caseId'
      fullPath: '/kasus/$caseId'
      preLoaderRoute: typeof AppKasusCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBantuanInsidentalRoute: typeof AppBantuanInsidentalRoute
  AppBantuanRutinRoute: typeof AppBantuanRutinRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonaturRoute: typeof AppDonaturRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppMustahikRoute: typeof AppMustahikRoute
  AppPengajuanBaruRoute: typeof AppPengajuanBaruRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppProgramRoute: typeof AppProgramRoute
  AppKasusCaseIdRoute: typeof AppKasusCaseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBantuanInsidentalRoute: AppBantuanInsidentalRoute,
  AppBantuanRutinRoute: AppBantuanRutinRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDonaturRoute: AppDonaturRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppMustahikRoute: AppMustahikRoute,
  AppPengajuanBaruRoute: AppPengajuanBaruRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppProgramRoute: AppProgramRoute,
  AppKasusCaseIdRoute: AppKasusCaseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
