import type { SipUser } from "./types";

// Mock user roster for the NGO admin prototype.
export const sipUsers: SipUser[] = [
  {
    id: "usr-001",
    name: "Nur Azizah",
    role: "pengurus",
    phone: "0812-3100-2188",
    region: "NGO Center",
    status: "Aktif",
  },
  {
    id: "usr-002",
    name: "Fikri Ramadhan",
    role: "admin",
    phone: "0813-8821-4409",
    region: "NGO Center",
    status: "Aktif",
  },
  {
    id: "usr-003",
    name: "Ahmad Ridwan",
    role: "verifikator",
    phone: "0857-7720-1199",
    region: "Bekasi",
    status: "Aktif",
  },
  {
    id: "usr-004",
    name: "Dewi Lestari",
    role: "verifikator",
    phone: "0821-1902-5521",
    region: "Bogor",
    status: "Aktif",
  },
  {
    id: "usr-005",
    name: "Haris Maulana",
    role: "verifikator",
    phone: "0812-6444-9012",
    region: "Jakarta Timur",
    status: "Aktif",
  },
  {
    id: "usr-006",
    name: "Siti Rohmah",
    role: "verifikator",
    phone: "0857-1100-3321",
    region: "Depok",
    status: "Aktif",
  },
  {
    id: "usr-007",
    name: "Bagus Prakoso",
    role: "verifikator",
    phone: "0812-9087-4432",
    region: "Kota Tangerang",
    status: "Aktif",
  },
  {
    id: "usr-008",
    name: "Lukman Hakim",
    role: "verifikator",
    phone: "0821-7765-8890",
    region: "Karawang",
    status: "Aktif",
  },
  {
    id: "usr-009",
    name: "Rina Marlina",
    role: "verifikator",
    phone: "0813-4456-2210",
    region: "Bandung",
    status: "Nonaktif",
  },
  {
    id: "usr-010",
    name: "Abdul Somad",
    role: "pengurus",
    phone: "0812-3322-1144",
    region: "NGO Center",
    status: "Aktif",
  },
  {
    id: "usr-011",
    name: "Yuliana Sari",
    role: "admin",
    phone: "0857-6543-7788",
    region: "NGO Center",
    status: "Aktif",
  },
];
